#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source $HOME/.aliases

fpath=(~/.zsh/func $fpath)
compinit

r() {
  local f; f=(~/.zsh/func/*)
  unfunction $f:t 2> /dev/null
  autoload -U $f:t
}
